version: '3.9'

services:
  spark-scala:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: spark-scala
    volumes:
      - ./app:/app
    depends_on:
      - postgres
    networks:
      - scala-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - scala-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - scala-network

volumes:
  postgres_data:
    driver: local

networks:
  scala-network:
    driver: bridge
